### ISSUE TITLE
0.9.3.1 build error in coins.cpp: base operand of ‘->’ has non-pointer type ‘const CCoins’

### ISSUE THREAD

**Issue by allesklaar** [FeatherCoin/Feathercoin#142]
This is with the current Arch Linux build stack: QMake 3.0 using Qt  5.7.1, boost 1.62, gcc 6.2.1.

My build command was:

```
./autogen.sh
./configure --with-incompatible-bdb
make
```

Build fails at:

```
  CXX      coins.o
coins.cpp: In member function ‘double CCoinsViewCache::GetPriority(const CTransaction&, int)’:
coins.cpp:191:18: error: base operand of ‘->’ has non-pointer type ‘const CCoins’
         if (coins->nHeight <= nHeight) {
                  ^~
coins.cpp:192:84: error: base operand of ‘->’ has non-pointer type ‘const CCoins’
             dResult += (double)(coins.vout[txin.prevout.n].nValue) * (nHeight-coins->nHeight);
                                                                                    ^~
```

**Comment by allesklaar** [comment]
I reported the coins.cpp issue seperately in #127.

**Comment by wrapperband** [comment]
Theres a couple of things that might help 
If you checkout 0.9.6 do you get the same problem (i.e. its fixed)

If you do, can you pass us the makefile, we don't maintain  the arch set-up, is there a link?
so we can try and reproduce the error.

**Comment by allesklaar** [comment]
@wrapperband 

coins.o in 0.9.6 builds fine as of f6cbba726e8f70a9aed2e738f5a6f13e941ebd91.

Build fails at net.o now. The error:

```
  CXX      net.o
net.cpp: In function 'void ThreadMapPort()':
net.cpp:1098:68: error: invalid conversion from 'int*' to 'unsigned char' [-fpermissive]
     devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
                                                                    ^~~~~~
net.cpp:1098:74: error: too few arguments to function 'UPNPDev* upnpDiscover(int, const char*, const char*, int, int, unsigned char, int*)'
     devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
                                                                          ^
In file included from net.cpp:25:0:
/usr/include/miniupnpc/miniupnpc.h:62:1: note: declared here
 upnpDiscover(int delay, const char * multicastif,
 ^~~~~~~~~~~~
make[3]: *** [Makefile:899: net.o] Error 1
make[3]: Leaving directory '/tmp/feathercoin/Feathercoin/src'
make[2]: *** [Makefile:921: all-recursive] Error 1
make[2]: Leaving directory '/tmp/feathercoin/Feathercoin/src'
make[1]: *** [Makefile:675: all] Error 2
make[1]: Leaving directory '/tmp/feathercoin/Feathercoin/src'
make: *** [Makefile:510: all-recursive] Error 1
```

An easy way to try reproducing this on Arch Linux for you would be in Docker. Follow the simple procedure on https://github.com/czka/archlinux-docker to create a current Arch Linux Docker image, run a container from it, install FTC dependencies with `pacman -Syu package_name1 package_name2 ...` in the container, clone FTC Git repo and try a build.

**Comment by aciddude** [comment]
@allesklaar 

0.9.6 should build perfectly with Qt 5.7.1, boost 1.62, gcc 6.2.1.

The only difference is I've never used QMake.  I'm going to create a Arch Linux VM and do a build, I'll write down my steps and post back here.

**Comment by aciddude** [comment]
@allesklaar 

Please note Feathercoin v0.9.6 is still a development/pre-release version, I still recommend you wait for this to be a full release before building. 

I was able to build 0.9.6 with this: 

VMware Player: Arch Linux 2017.01.01 

Dependency Versions: 
autoconf 2.69-4
automake 1.15-2
gcc 6.3.1-1
boost 1.63.0-1
qrencode 3.4.4-1
protobuf-3.0.2-3
qt5 5.7.1-1
miniupnpc 2.0-1
cmake 3.7.1-1


Step 1: Install dependancies: 

```
pacman -S git
pacman -S autoconf	
pacman -S automake
pacman -S gcc		
pacman -S db
pacman -S boost
pacman -S qrencode
pacman -S protobuf
pacman -S qt5	
pacman -S miniupnpc
```

## Needed for Zxing 
`pacman -S cmake`

Step 2, build and install Zxing (needed if you want QRcodes in Feathercoin-QT) 
```
git clone https://github.com/glassechidna/zxing-cpp.git
cd zxing-cpp
mkdir build
cd build
export CXXFLAGS="-fPIC"
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
make
make install
```
You then need to go and edit the LuminanceSource.h  file in /usr/local/include/zxing  and change line 30 to "public:"   *instead of private* 
`nano /usr/local/include/zxing/LuminanceSource.h`

Step 3: Build Feathercoind + Feathercoin-QT
```
git clone -b 0.9.6 https://github.com/FeatherCoin/Feathercoin.git FTC096
cd FTC096
./autogen.sh
./configure --prefix=/home/feathercoin --disable-tests --with-gui=qt5 --with-incompatible-bdb --without-miniupnpc
make
make install

```
Let me know how you get on. 


I hope this helps someone.

**Comment by wrapperband** [comment]
Thanks Aciddude, I see you've add that information to the guides on the forum.

http://forum.feathercoin.com/topic/8786/guide-build-feathercoind-feathercoin-qt-v0-9-6-on-arch-linux-2017-01-01

**Comment by wellenreiter01** [comment]
Solved in 0.9.6
