### ISSUE TITLE
Network fork

### ISSUE THREAD

**Issue by kha0S** [FeatherCoin/Feathercoin#95]
Network as forked. As far as I can tell, nodes running 0.11.2 are not able to process block 1114311:

```
2016-03-04 09:06:30 InvalidChainFound: invalid block=1c1efa7d298c02ccf62227c8396a53d16a4094b6816821dba717c525a1e53dfc  height=1114311  log2_work=57.94026  date=2016-03-04 01:19:19
2016-03-04 09:06:30 ERROR: ConnectTip(): ConnectBlock 1c1efa7d298c02ccf62227c8396a53d16a4094b6816821dba717c525a1e53dfc failed
2016-03-04 09:06:30 InvalidChainFound: invalid block=1c1efa7d298c02ccf62227c8396a53d16a4094b6816821dba717c525a1e53dfc  height=1114311  log2_work=57.94026  date=2016-03-04 01:19:19

```

Same block on version 0.9.3:

```
2016-03-04 01:19:33 UpdateTip: new best=1c1efa7d298c02ccf62227c8396a53d16a4094b6816821dba717c525a1e53dfc  height=1114311  log2_work=57.94026  tx=2538101  date=2016-03-04 01:19:19 progress=1.000000
2016-03-04 01:20:08 ConnectBlock hashPrevBlock=1c1efa7d298c02ccf62227c8396a53d16a4094b6816821dba717c525a1e53dfc 
2016-03-04 01:20:08 ConnectBlock view.GetBestBlock()=1c1efa7d298c02ccf62227c8396a53d16a4094b6816821dba717c525a1e53dfc 

```

**Comment by wellenreiter01** [comment]
correct, the only working version is 0.9.3
A patch for 0.11.2 will be created as soon as possible

**Comment by wellenreiter01** [comment]
fixed with #96

**Comment by kha0S** [comment]
I can't compile with libboost-1.58:

```
rpcrawtransaction.cpp:299:77:   required from here
/usr/include/boost/variant/get.hpp:178:5: error: invalid application of ‘sizeof’ to incomplete type ‘boost::STATIC_ASSERTION_FAILURE<false>’
     BOOST_STATIC_ASSERT_MSG(

```

It does compile with libboost-1.6

**Comment by ghostlander** [comment]
Works for me with Boost v1.59.
