### ISSUE TITLE
broken build on UNIX -- Illumos amd64 (SunOS 5.11)

### ISSUE THREAD

**Issue by beattidp** [FeatherCoin/Feathercoin#6]
Using Joyent SmartOS (SmartMachine image base64 13.3.1), with pkgsrc 2013Q4/x86_64.
( i.e.  'sudo pkgin install git openssl db4 gcc47 boost build-essential miniupnpd' )
Looks kind-of broken to me.  Any comments/observations?

```
[admin@sun02 ~/work]$ env GIT_SSL_NO_VERIFY=true  git clone https://github.com/FeatherCoin/Feathercoin-0.8.5.git
[admin@sun02 ~/work]$ cd ./Feathercoin-0.8.5/src/
[admin@sun02 ~/work/Feathercoin-0.8.5/src]$ make -f makefile.unix

# ( and it builds okay for a short while, until: )

make[1]: Leaving directory '/home/admin/work/Feathercoin-0.8.5/src/leveldb'
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/home/admin/work/Feathercoin-0.8.5/src -I/home/admin/work/Feathercoin-0.8.5/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/home/admin/work/Feathercoin-0.8.5/src/leveldb/include -I/home/admin/work/Feathercoin-0.8.5/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/alert.d -o obj/alert.o alert.cpp
alert.cpp:19:1: error: reference to 'map' is ambiguous
In file included from compat.h:24:0,
                 from netbase.h:11,
                 from util.h:30,
                 from alert.h:13,
                 from alert.cpp:11:
/usr/include/net/if.h:97:9: error: candidates are: struct map
In file included from /opt/local/gcc47/include/c++/map:61:0,
                 from alert.cpp:9:
/opt/local/gcc47/include/c++/bits/stl_map.h:90:11: error:                 template<class _Key, class _Tp, class _Compare, class _Alloc> class std::map
alert.cpp:19:1: error: 'map' does not name a type
alert.cpp: In static member function 'static CAlert CAlert::getAlertByHash(const uint256&)':
alert.cpp:162:9: error: reference to 'map' is ambiguous
In file included from compat.h:24:0,
                 from netbase.h:11,
                 from util.h:30,
                 from alert.h:13,
                 from alert.cpp:11:
/usr/include/net/if.h:97:9: error: candidates are: struct map
In file included from /opt/local/gcc47/include/c++/map:61:0,
                 from alert.cpp:9:
/opt/local/gcc47/include/c++/bits/stl_map.h:90:11: error:                 template<class _Key, class _Tp, class _Compare, class _Alloc> class std::map
alert.cpp:162:20: error: expected primary-expression before ',' token
alert.cpp:162:28: error: expected primary-expression before '>' token
alert.cpp:162:40: error: missing template arguments before 'mi'
alert.cpp:162:40: error: expected ';' before 'mi'
alert.cpp:163:12: error: 'mi' was not declared in this scope
alert.cpp:163:18: error: 'mapAlerts' was not declared in this scope
alert.cpp: In member function 'bool CAlert::ProcessAlert(bool)':
alert.cpp:201:14: error: reference to 'map' is ambiguous
In file included from compat.h:24:0,
                 from netbase.h:11,
                 from util.h:30,
                 from alert.h:13,
                 from alert.cpp:11:
/usr/include/net/if.h:97:9: error: candidates are: struct map
In file included from /opt/local/gcc47/include/c++/map:61:0,
                 from alert.cpp:9:
/opt/local/gcc47/include/c++/bits/stl_map.h:90:11: error:                 template<class _Key, class _Tp, class _Compare, class _Alloc> class std::map
alert.cpp:201:25: error: expected primary-expression before ',' token
alert.cpp:201:33: error: expected primary-expression before '>' token
alert.cpp:201:45: error: missing template arguments before 'mi'
alert.cpp:201:45: error: expected ';' before 'mi'
alert.cpp:201:69: error: 'mi' was not declared in this scope
alert.cpp:201:75: error: 'mapAlerts' was not declared in this scope
alert.cpp:221:9: error: 'mapAlerts' was not declared in this scope
alert.cpp:232:9: error: 'mapAlerts' was not declared in this scope
makefile.unix:173: recipe for target 'obj/alert.o' failed
make: *** [obj/alert.o] Error 1
[admin@sun02 ~/work/Feathercoin-0.8.5/src]$ 

[admin@sun02 ~/work/Feathercoin-0.8.5/src]$ gcc --version | head -n1
gcc (GCC) 4.7.3

[admin@sun02 ~/work/Feathercoin-0.8.5/src]$ uname -sr
SunOS 5.11
```
